Add support for Xiaomi LYWSD03MMC ATC1441 Firmware
shmuelzon/esp32-ble2mqtt pull request #94
Opened 2021-01-25 13:50 UTC by ozonejunkieau

I've added support for the advertisement format used by the ATC1441 custom firmware for the Xiaomi LYWSD03MMC temperature and humidity sensor.

This is based on the format documented here: https://github.com/atc1441/ATC_MiThermometer

2021-01-25 20:04 UTC, shmuelzon requested changes
Thank you for this pull request!
Most of my comments are nitpicking around my coding style, if you don't want to deal with it, I can handle them myself.

2021-01-25 20:04 UTC, shmuelzon commented on main/broadcasters.c
> +    uint8_t *data = esp_ble_resolve_adv_data(adv_data, ESP_BLE_AD_TYPE_SERVICE_DATA, &len);
This line exceeds 80 characters, please break it

2021-01-25 20:04 UTC, shmuelzon commented on main/broadcasters.c
> +static void atc1441_temp_hum_metadata_get(uint8_t *adv_data, size_t adv_data_len,
This line exceeds 80 characters, please break it

2021-01-26 05:28 UTC, ozonejunkieau commented on main/broadcasters.c
> +    }
I've left this as I wrapped the line above to be less than 80 characters.

2021-01-26 05:29 UTC, ozonejunkieau commented on main/broadcasters.c
> +
So, the reason I included this is so I can do the decoding client side and maintain most of the existing Python code I have to log the output into InfluxDB. I've commented it out so it now is not part of the default behaviour.

2021-01-26 05:30 UTC, ozonejunkieau commented
Thanks for the review, I think I found all the changes. My apologies for extraneous white space, I spend most of my time in Python! :-D

2021-01-26 06:37 UTC, shmuelzon requested changes

2021-01-26 06:37 UTC, shmuelzon commented on main/broadcasters.c
> +   See: https://github.com/atc1441/ATC_MiThermometer */
```c
/* ATC1441 Firmware for the Xiaomi Thermometer LYWSD03MMC Temperature and
 * Humidity Sensor, see: https://github.com/atc1441/ATC_MiThermometer */
```

2021-01-26 06:37 UTC, shmuelzon commented on main/broadcasters.c
> +     le16toh(atc1441_data->service_uuid) != ATC1441_TEMP_HUM_SERVICE_UUID)
This needs to be indented 4 spaces, not 1

2021-01-26 06:37 UTC, shmuelzon commented on main/broadcasters.c
> +static broadcaster_ops_t atc1441_temp_hum_ops = {
Need a single line break between 535 and 536

2021-01-26 06:37 UTC, shmuelzon commented on main/broadcasters.c
> +
I'd rather not have this committed, even if it's commented out

2021-01-26 06:38 UTC, shmuelzon commented
Sorry for the nitpicking, I'm just trying to maintain a single style

2021-01-28 10:36 UTC, ozonejunkieau commented
Closed to recreate from a different source branch.

2021-01-28 10:36 UTC, closed without merging